# Generated by Django 5.1.3 on 2025-01-20 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='date',
        ),
    ]
