# Generated by Django 5.1.3 on 2025-01-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
