# Generated by Django 5.1.3 on 2025-01-03 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_filled',
        ),
    ]
