# Generated by Django 5.1.3 on 2025-01-20 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='date',
            new_name='flight_date',
        ),
    ]
