# Generated by Django 5.1.3 on 2025-01-20 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_flight_flight_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='flight_date',
        ),
    ]
